Need to validate appinit_values has data
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/me/volatility/volatility/commands.py", line 103, in execute
    data = self.calculate()
  File "/home/me/other_plugins/Autoruns.py", line 461, in calculate
    self.appinit_dlls = self.get_appinit_dlls()
  File "/home/me/other_plugins/Autoruns.py", line 193, in get_appinit_dlls
    appinit_dlls = appinit_values.replace('\x00', '').split(' ')
AttributeError: 'NoneType' object has no attribute 'replace'